name: Publish to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: 11 4 * * *

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # SVG optimisation
          sudo npm install -g svgo

      - name: Generate Website
        run: |
          mkdir public
          cp style.css public/style.css
          cp feather.min.js public/feather.min.js
          go run main.go -t ${{ secrets.GITHUB_TOKEN }} -o public/index.html

          # Background
          julia --project -e 'using Pkg; Pkg.instantiate()'
          julia --project background.jl

          # Optimise background
          svgo background.svg -o background.min.svg
          mv background.min.svg public/background.svg

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@d3b77e62017a60cdf55ceffc6c263f1f357f4c1b # 2.1.2
        with:
          target_branch: gh-pages
          build_dir: public
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
