name: Publish to GitHub Pages

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 11 4 * * *

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install accessibility CI tool
        run: sudo npm install -g pa11y-ci --unsafe-perm=true --allow-root

      - name: Generate Website
        run: |
          mkdir public
          cp style.css public/style.css
          cp feather.min.js public/feather.min.js
          go run main.go -t ${{ secrets.GITHUB_TOKEN }} -o public/index.html
          cp background.min.svg public/background.svg

      - name: Run accessibility checks
        run: |
          # Server script based on https://gist.github.com/tdpreece/91c6b0305cc7a151e03f
          # Start server
          python3 -m http.server 8000 -d public &> /dev/null &
          pid="$!"
          sleep 3

          # Run checks
          pa11y-ci

          # Kill server
          kill "$pid"

      - name: Create website archive for debugging
        run: tar --use-compress-program zstd -cf your-first-julia-pr.tar.zst public/

      - name: Upload website archive for debugging
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: your-first-julia-pr.tar.zst

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@d3b77e62017a60cdf55ceffc6c263f1f357f4c1b # 2.1.2
        with:
          target_branch: gh-pages
          build_dir: public
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
